### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by chaozai1028l** [ysrc/xunfeng#130]
嗨 ，又来麻烦你们了。
centos7 安装流程到最后，根据实际情况修改(端口和目录需对应好) Conifg.py 和 Run.sh 文件
Config.py 修改 PORT 27017  DBPASSWORD  修改之前在添加db.createUser的时候创建的密码
Run.sh  修改 XUNFENG_DB=/usr/lib/mongod       nohup mongod --port 27017
运行 Run.sh 的时候 显示 重定向标准错误到标准输出
浏览器访问ip：27017 的时候好像并没有成功
请问 我哪里出错了

**Comment by chaozai1028l** [comment]
我在查看 /var/log/xunfeng里  web.log 如下
Traceback (most recent call last):
  File "./Run.py", line 5, in <module>
    app.run(threaded=True, port=80,host='0.0.0.0')
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 739, in run_simple
    inner()
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in inner
    fd=fd)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 587, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 504, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
是我开启了其它服务占用了 127.0.0.1 ？

**Comment by ihacku** [comment]
巡风 web 界面 端口是80，不熟悉一些背景知识的话，可以搜一些别人写的巡风部署的文章看下。
