### ISSUE TITLE
一键安装，xunfeng_aider启动失败

### ISSUE THREAD

**Issue by daniel0720** [ysrc/xunfeng#190]
Ubuntu16.04操作系统，采用一键安装方式安装成功，xunfeng服务也能启动成功。但是查看/var/log/xunfeng/xunfeng.log，发现xunfeng_aider服务也就是Aider.py程序没有运行成功。

> 2019-02-27 15:00:46,006 INFO Set uid to user 0 succeeded
2019-02-27 15:00:46,014 INFO RPC interface 'supervisor' initialized
2019-02-27 15:00:46,014 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-02-27 15:00:46,015 INFO daemonizing the supervisord process
2019-02-27 15:00:46,015 INFO supervisord started with pid 9888
2019-02-27 15:00:46,124 INFO spawned: 'xunfeng_aider' with pid 9891
2019-02-27 15:00:46,125 INFO spawned: 'xunfeng_nascan' with pid 9892
2019-02-27 15:00:46,127 INFO spawned: 'xunfeng_web' with pid 9893
2019-02-27 15:00:46,128 INFO spawned: 'xunfeng_vulscan' with pid 9894
2019-02-27 15:00:46,130 INFO spawned: 'xunfeng_db' with pid 9895
2019-02-27 15:00:46,163 INFO exited: xunfeng_aider (exit status 1; not expected)
2019-02-27 15:00:47,408 INFO spawned: 'xunfeng_aider' with pid 10003
2019-02-27 15:00:47,409 INFO success: xunfeng_nascan entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-02-27 15:00:47,409 INFO success: xunfeng_web entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-02-27 15:00:47,409 INFO success: xunfeng_vulscan entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-02-27 15:00:47,409 INFO success: xunfeng_db entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-02-27 15:00:47,433 INFO exited: xunfeng_aider (exit status 1; not expected)
2019-02-27 15:00:49,437 INFO spawned: 'xunfeng_aider' with pid 10004
2019-02-27 15:00:49,459 INFO exited: xunfeng_aider (exit status 1; not expected)
2019-02-27 15:00:52,464 INFO spawned: 'xunfeng_aider' with pid 10007
2019-02-27 15:00:52,485 INFO exited: xunfeng_aider (exit status 1; not expected)
2019-02-27 15:00:53,487 INFO gave up: xunfeng_aider entered FATAL state, too many start retries too quickly

如果此时停止xunfeng服务，然后单独运行Aider.py，则报Address already in use的错误。
>Traceback (most recent call last):
  File "Aider.py", line 38, in <module>
    dns.bind(('0.0.0.0',53))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

53端口被占用？
使用netstat -anltp | grep 53命令查看端口情况，
>tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      2326/dnsmasq    
tcp        0      0 192.168.3.111:55452     192.30.253.125:443      ESTABLISHED 4146/chrome --no-de

请问这种情况该怎么解决？

**Comment by daniel0720** [comment]
已经搞定，确实是dnsmasq的问题。
ubuntu自动开机启动dnsmasq，占用53端口，因此需要停止dnsmasq。
以root用户修改/etc/NetworkManager/NetworkManager.conf，注释掉dns=dnsmasq，即前面加#
