### ISSUE TITLE
sh run.sh不能执行的问题

### ISSUE THREAD

**Issue by stevenchen0x01** [ysrc/xunfeng#222]
**sh.run sh**
[root@localhost xunfeng-master]# nohup: redirecting stderr to stdout
nohup: redirecting stderr to stdout
nohup: redirecting stderr to stdout
nohup: redirecting stderr to stdout
nohup: redirecting stderr to stdout

**db.log**
[root@localhost xunfeng]# cat db.log 
2019-07-29T01:58:26.285-0400 I CONTROL  [initandlisten] MongoDB starting : pid=12080 port=27017 dbpath=/var/lib/mongodb 64-bit host=localhost.localdomain
2019-07-29T01:58:26.285-0400 I CONTROL  [initandlisten] db version v3.2.22
2019-07-29T01:58:26.285-0400 I CONTROL  [initandlisten] git version: 105acca0d443f9a47c1a5bd608fd7133840a58dd
2019-07-29T01:58:26.285-0400 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2019-07-29T01:58:26.285-0400 I CONTROL  [initandlisten] allocator: tcmalloc
2019-07-29T01:58:26.285-0400 I CONTROL  [initandlisten] modules: none
2019-07-29T01:58:26.285-0400 I CONTROL  [initandlisten] build environment:
2019-07-29T01:58:26.285-0400 I CONTROL  [initandlisten]     distmod: rhel70
2019-07-29T01:58:26.285-0400 I CONTROL  [initandlisten]     distarch: x86_64
2019-07-29T01:58:26.285-0400 I CONTROL  [initandlisten]     target_arch: x86_64
2019-07-29T01:58:26.285-0400 I CONTROL  [initandlisten] options: { net: { port: 27017 }, security: { authorization: "enabled" }, storage: { dbPath: "/var/lib/mongodb" } }
2019-07-29T01:58:26.349-0400 E NETWORK  [initandlisten] listen(): bind() failed errno:98 Address already in use for socket: 0.0.0.0:27017
2019-07-29T01:58:26.349-0400 E NETWORK  [initandlisten]   addr already in use
2019-07-29T01:58:26.349-0400 E STORAGE  [initandlisten] Failed to set up sockets during startup.
2019-07-29T01:58:26.349-0400 I CONTROL  [initandlisten] dbexit:  rc: 48

 **web.log**
[root@localhost xunfeng]# cat web.log 
Traceback (most recent call last):
  File "web.py", line 1, in <module>
    from views.view import app
  File "/root/xunfeng-master/views/__init__.py", line 3, in <module>
    from flask import Flask
ImportError: No module named flask

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-biRyF2/pycparser/setup.py'"'"'; __file__='"'"'/tmp/pip-install-biRyF2/pycparser/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-biRyF2/pycparser/
    Complete output (17 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-biRyF2/pycparser/setup.py", line 65, in <module>
        cmdclass={'install': install, 'sdist': sdist},
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2444, in resolve
        raise ImportError(str(exc))
    ImportError: 'module' object has no attribute 'check_specifier'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Medicean** [comment]
27017 已经被占用了，仔细阅读 log 哈

```
2019-07-29T01:58:26.349-0400 E NETWORK [initandlisten] listen(): bind() failed errno:98 Address already in use for socket: 0.0.0.0:27017
2019-07-29T01:58:26.349-0400 E NETWORK [initandlisten] addr already in use
```
