### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wifislax** [ysrc/xunfeng#46]
版本：
Name: paramiko
Version: 2.0.0

报错：No handlers could be found for logger “paramiko.transport”

**Comment by Dee-Ng** [comment]
@ywolf 
添加到crack_ssh.py 可修复
`paramiko.util.logging.getLogger('paramiko.transport').addHandler(paramiko.util.logging.NullHandler())`

**Comment by wifislax** [comment]
@Dee-Ng 

def check(ip, port, timeout):
    user_list = ['root', 'admin', 'oracle', 'weblogic']
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    paramiko.util.logging.getLogger('paramiko.transport').addHandler(paramiko.util.logging.NullHandler())
    for user in user_list:
        for pass_ in PASSWORD_DIC:


这样子的么

**Comment by ywolf** [comment]
@Dee-Ng 是什么原理呢，那个报错测试好像不影响功能

**Comment by Dee-Ng** [comment]
@ywolf那个报错其实是连接非ssh端口时候都会出现，加上这一行其实是关闭日志的输出，也是没有影响的。

**Comment by wifislax** [comment]
127.0.0.1 - - [12/Jan/2017 07:51:12] "GET /pullupdate HTTP/1.1" 302 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 196, in execute
    write(data)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 164, in write
    self.send_header(key, value)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
127.0.0.1 - - [12/Jan/2017 07:51:17] "GET /pullupdate HTTP/1.1" 302 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 196, in execute
    write(data)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 164, in write
    self.send_header(key, value)
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
127.0.0.1 - - [12/Jan/2017 07:51:19] "GET /pullupdate HTTP/1.1" 302 -
127.0.0.1 - - [12/Jan/2017 07:51:19] "GET /500 HTTP/1.1" 200 -


这种又是咋回事。
