### ISSUE TITLE
服务器配置时最后一步报错

### ISSUE THREAD

**Issue by lianfeng30** [ysrc/xunfeng#60]
cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)

数据库密码已经统一修改

执行 ./Run.sh
[root@vm]# ./Run.sh 
nohup: 重定向标准错误到标准输出
nohup: 重定向标准错误到标准输出
nohup: 重定向标准错误到标准输出
nohup: 重定向标准错误到标准输出

日志：

[root@vm]# cat web.log 
Traceback (most recent call last):
  File "./Run.py", line 1, in <module>
    from views.View import app
  File "/home/long/views/__init__.py", line 12, in <module>
    app.config.get('DBUSERNAME'), app.config.get('DBPASSWORD'))
  File "/home/long/views/lib/Conn.py", line 13, in __init__
    self.coll.authenticate(username, password)
  File "/usr/lib64/python2.7/site-packages/pymongo/database.py", line 1048, in authenticate
    connect=True)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 500, in _cache_credentials
    writable_preferred_server_selector)
  File "/usr/lib64/python2.7/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/usr/lib64/python2.7/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:65521: [Errno 111] Connection refused

[root@vm]# cat vul.log 
Traceback (most recent call last):
  File "./vulscan/VulScan.py", line 20, in <module>
    na_db.authenticate(ProductionConfig.DBUSERNAME, ProductionConfig.DBPASSWORD)
  File "/usr/lib64/python2.7/site-packages/pymongo/database.py", line 1048, in authenticate
    connect=True)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 500, in _cache_credentials
    writable_preferred_server_selector)
  File "/usr/lib64/python2.7/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/usr/lib64/python2.7/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:65521: [Errno 111] Connection refused

[root@vm]# cat scan.log 
Traceback (most recent call last):
  File "./nascan/NAScan.py", line 4, in <module>
    from lib.common import *
  File "/home/long/nascan/lib/common.py", line 2, in <module>
    import mongo
  File "/home/long/nascan/lib/mongo.py", line 8, in <module>
    na_db.authenticate(ProductionConfig.DBUSERNAME, ProductionConfig.DBPASSWORD)
  File "/usr/lib64/python2.7/site-packages/pymongo/database.py", line 1048, in authenticate
    connect=True)
  File "/usr/lib64/python2.7/site-packages/pymongo/mongo_client.py", line 500, in _cache_credentials
    writable_preferred_server_selector)
  File "/usr/lib64/python2.7/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "/usr/lib64/python2.7/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:65521: [Errno 111] Connection refused

[root@vm# cat db.log 
2017-03-02T11:53:12.418+0800 I CONTROL  [initandlisten] MongoDB starting : pid=2777 port=65521 dbpath=/var/lib/mongodb 64-bit host=vm-sec
2017-03-02T11:53:12.419+0800 I CONTROL  [initandlisten] db version v3.2.12
2017-03-02T11:53:12.419+0800 I CONTROL  [initandlisten] git version: ef3e1bc78e997f0d9f22f45aeb1d8e3b6ac14a14
2017-03-02T11:53:12.419+0800 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2017-03-02T11:53:12.419+0800 I CONTROL  [initandlisten] allocator: tcmalloc
2017-03-02T11:53:12.419+0800 I CONTROL  [initandlisten] modules: none
2017-03-02T11:53:12.419+0800 I CONTROL  [initandlisten] build environment:
2017-03-02T11:53:12.419+0800 I CONTROL  [initandlisten]     distmod: rhel70
2017-03-02T11:53:12.419+0800 I CONTROL  [initandlisten]     distarch: x86_64
2017-03-02T11:53:12.419+0800 I CONTROL  [initandlisten]     target_arch: x86_64
2017-03-02T11:53:12.419+0800 I CONTROL  [initandlisten] options: { net: { port: 65521 }, security: { authorization: "enabled" }, storage: { dbPath: "/var/lib/mongodb" } }
2017-03-02T11:53:12.457+0800 I -        [initandlisten] Detected data files in /var/lib/mongodb created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2017-03-02T11:53:12.457+0800 W -        [initandlisten] Detected unclean shutdown - /var/lib/mongodb/mongod.lock is not empty.
2017-03-02T11:53:12.457+0800 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
2017-03-02T11:53:12.457+0800 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-03-02T11:53:12.695+0800 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-03-02T11:53:12.695+0800 I CONTROL  [initandlisten] 
2017-03-02T11:53:12.695+0800 I CONTROL  [initandlisten] 
2017-03-02T11:53:12.695+0800 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-03-02T11:53:12.695+0800 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-03-02T11:53:12.695+0800 I CONTROL  [initandlisten] 
2017-03-02T11:53:12.695+0800 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2017-03-02T11:53:12.695+0800 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-03-02T11:53:12.695+0800 I CONTROL  [initandlisten] 
2017-03-02T11:53:12.696+0800 F INDEX    [initandlisten] Cannot start mongod when the featureCompatibilityVersion is higher than 3.2. See http://dochub.mongodb.org/core/3.4-feature-compatibility.
2017-03-02T11:53:12.696+0800 I -        [initandlisten] Fatal Assertion 40352
2017-03-02T11:53:12.696+0800 I -        [initandlisten] 

***aborting after fassert() failure

...

**Comment by lianfeng30** [comment]
搞错了。...

**Comment by Gotric** [comment]
同样遇到这个问题 解决了么？
