### ISSUE TITLE
最后一步启动不成功

### ISSUE THREAD

**Issue by Gotric** [ysrc/xunfeng#83]
最后一步运行
sh Run.sh
出现
[root@localhost xunfeng]# nohup: redirecting stderr to stdout
nohup: redirecting stderr to stdout
nohup: redirecting stderr to stdout
nohup: redirecting stderr to stdout
nohup: redirecting stderr to stdout

日志：

**vi db.log**

2017-04-05T13:59:56.466+0800 I CONTROL  [initandlisten] db version v3.2.12
2017-04-05T13:59:56.466+0800 I CONTROL  [initandlisten] git version: ef3e1bc78e997f0d9f22f45aeb1d8e3b6ac14a14
2017-04-05T13:59:56.466+0800 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
2017-04-05T13:59:56.466+0800 I CONTROL  [initandlisten] allocator: tcmalloc
2017-04-05T13:59:56.466+0800 I CONTROL  [initandlisten] modules: none
2017-04-05T13:59:56.467+0800 I CONTROL  [initandlisten] build environment:
2017-04-05T13:59:56.467+0800 I CONTROL  [initandlisten]     distmod: rhel62
2017-04-05T13:59:56.467+0800 I CONTROL  [initandlisten]     distarch: x86_64
2017-04-05T13:59:56.467+0800 I CONTROL  [initandlisten]     target_arch: x86_64
2017-04-05T13:59:56.467+0800 I CONTROL  [initandlisten] options: { net: { port: 65521 }, security: { authorization: "enabled" }, storage: { dbPath: "/var/lib/mongo" } }
2017-04-05T13:59:56.503+0800 E NETWORK  [initandlisten] listen(): bind() failed errno:98 Address already in use for socket: 0.0.0.0:65521
2017-04-05T13:59:56.503+0800 E NETWORK  [initandlisten]   addr already in use
2017-04-05T13:59:56.503+0800 E STORAGE  [initandlisten] Failed to set up sockets during startup.
2017-04-05T13:59:56.503+0800 I CONTROL  [initandlisten] dbexit:  rc: 48

**vi web.log**
Traceback (most recent call last):
  File "./Run.py", line 5, in <module>
    app.run(threaded=True, port=80,host='0.0.0.0')
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python2.6/site-packages/werkzeug/serving.py", line 717, in run_simple
    s.bind((hostname, port))
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use

**Comment by Medicean** [comment]
> socket.error: [Errno 98] Address already in use

It means the port 80 is occupied by other programs.

**Comment by Gotric** [comment]
应该在哪里改xunfneg的启动端口呢

**Comment by Medicean** [comment]
@Gotric https://github.com/ysrc/xunfeng/blob/master/Run.py#L5

**Comment by Gotric** [comment]
已解决 谢谢
